server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver